server:
  port: 8096
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
spring:
  application:
    name: cloud-provider
  cloud:
    config:
      server:
         git:
           password: kxf20131125
           username: old-rabbit
           uri: https://github.com/old-rabbit/springcloud.git
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/1906d?useUnicode=true&characterEncoding=utf-8
mybatis:
  config-locations: classpath:mapping/confg.xml
  mapper-locations: classpath:mapping/mapper/*.xml
  type-aliases-package: com.jk.model  




